---
title: "reworking your workflow"
subtitle: "combining data analysis and reporting with dynamic documents"
author: "Christof Neumann"
institute: "RTG Understanding Social Relationships"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

```{css, echo = FALSE}
.XC .remark-code * {
  background-color: antiquewhite!important;
}
.XC2 .remark-code, .XC2 .remark-code * {
  background-color: seashell!important;
  # text-shadow: 0 0 5px #333;
}
.content-box { 
    box-sizing: border-box;
    background-color: #e2e2e2;
}
.content-box-yellow {
  box-sizing: border-box;
  border-radius: 15px;
  margin: 0 0 15px;
  overflow: hidden;
  padding: 0px 20px 0px 20px;
  width: 100%;
}
.content-box-blue { background-color: #F0F8FF; }
.content-box-yellow { background-color: #fef5c4; }

```

```{r, echo=FALSE}
check_for_package <- function(p) {
  res <- suppressMessages(suppressWarnings(require(p, character.only = TRUE)))
  res
}

make_placeholder <- function(header, missingpackage) {
  cat(paste0("## ", header, "\n\n", 
             "- didn't find package `", missingpackage, "`", "\n\n", 
             "- will not include this slide here",  "\n\n"))
}


fast_override <- TRUE

```


```{r, child="bitsandpieces/content.Rmd"}

```


